pay:
  wxpay:
    # 应用ID，申请太麻烦了，先用下别人的吧
    appID: wx8397f8696b538317
    # 商户ID
    mchID: 1473426802
    # 秘钥
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    # 从微信商户平台下载的安全证书存放的路径、放在resources下面,切记一定要看看target目录下的class文件下有没有打包apiclient_cert.p12文件
    certPath: static/cert/wxpay/apiclient_cert.p12
    # 微信支付成功的异步通知接口
    payNotifyUrl: https://jelly.utools.club/api/v1/pay/wx/notify